# GitHub Actions configuration file : Continuous Integration

name: Continuous integration

# Trigger the workflow on push or pull request, for master branch only.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  windows-build:
    name: Test Windows build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Install NSIS
      run: .\install-nsis.ps1 -NoPause
    - name: Install OpenSSL
      run: .\install-openssl.ps1 -NoPause
    - name: Build libsrt
      run: .\build-all.ps1 -NoPause
    - name: Test installer
      run: |
        Get-ChildItem installers
        $bin = Get-ChildItem installers -Recurse -Include 'libsrt*.exe' | Select-Object -Last 1
        Start-Process -FilePath $bin.FullName -ArgumentList @("/S") -Wait
        Get-ChildItem 'C:\Program Files*\libsrt' -Recurse

  windows-release:
    name: Test installation from latest published release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Install libsrt
      run: .\install-libsrt.ps1 -GitHubActions -NoPause
    - name: Check installation
      run: |
        # Check if the environment variable is correctly passed from job to job.
        Write-Output "LIBSRT='$($env:LIBSRT)'"
        Get-ChildItem 'C:\Program Files*\libsrt'
        Get-ChildItem $($env:LIBSRT)

