# GitHub Actions configuration file : Validate published releases

name: Release validation

# Trigger the workflow on published releases
on:
  release:
    types: [published]

jobs:
  install-release:
    name: Test installation of latest published release
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Install libsrt
      run: .\install-libsrt.ps1 -GitHubActions -NoPause
    - name: Check installation
      run: |
        # Check if the environment variable is correctly passed from job to job.
        Write-Output "LIBSRT='$($env:LIBSRT)'"
        Get-ChildItem 'C:\Program Files*\libsrt'
        Get-ChildItem $($env:LIBSRT)
